name: test_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin:
    path: ../plugin
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_lints: ^3.0.0
  pigeon:
    git:
      url: https://github.com/bc-lee/flutter-packages.git
      path: packages/pigeon
      ref: c510bd6b0cc0da652ae714f6ee8132a37e27310a

flutter:

  uses-material-design: true
